# This is an example neoforge.mods.toml file.
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
description='''
${mod_description}
'''

# Abhängigkeit zu NeoForge selbst
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

# Abhängigkeit zu Minecraft
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# --- HIER IST DIE NEUE ABHÄNGIGKEIT ZU PARAGLIDER ---
[[dependencies.${mod_id}]]
    modId="paraglider"
    type="required"
    versionRange="[21.1.5,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    type="required"
    versionRange="[4.8.4,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="xaeroworldmap"
    type="optional"
    versionRange="[1.40,)"
    ordering="AFTER"
    side="BOTH"